import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { GeneratedDocument } from "./types";

const styles = StyleSheet.create({
  page: { padding: 42, fontFamily: "Helvetica", fontSize: 10, color: "#16181d", lineHeight: 1.5 },
  kicker: { fontSize: 8, letterSpacing: 2, color: "#6f43ff", marginBottom: 12 },
  title: { fontSize: 26, lineHeight: 1.1, marginBottom: 10 },
  subtitle: { fontSize: 11, color: "#626a77", marginBottom: 18 },
  section: { marginTop: 24 },
  sectionTitle: { fontSize: 17, marginBottom: 6 },
  intro: { fontSize: 10, color: "#59606c", marginBottom: 10 },
  lesson: { marginTop: 12, paddingLeft: 10, borderLeftWidth: 2, borderLeftColor: "#6f43ff" },
  lessonTitle: { fontSize: 12, marginBottom: 4 },
  label: { fontSize: 8, color: "#6f43ff", textTransform: "uppercase", marginTop: 5 },
  text: { fontSize: 10, marginBottom: 5 },
  bullet: { fontSize: 9, marginLeft: 10, marginBottom: 3 },
  box: { marginTop: 7, padding: 8, backgroundColor: "#f5f2ff" },
  footer: { position: "absolute", bottom: 22, left: 42, right: 42, fontSize: 7, color: "#8c929c" }
});

export function CoursePdf({ doc }: { doc: GeneratedDocument }) {
  return <Document title={doc.title} author="CourseForge">
    <Page size="A4" style={styles.page}>
      <Text style={styles.kicker}>COURSEFORGE EXPORT</Text>
      <Text style={styles.title}>{doc.title}</Text>
      <Text style={styles.subtitle}>{doc.subtitle}</Text>
      <Text style={styles.text}>{doc.summary}</Text>
      <Text style={styles.label}>Learning outcomes</Text>
      {doc.learningOutcomes.map((x, i) => <Text key={i} style={styles.bullet}>• {x}</Text>)}
      {doc.sections.map((section, i) => <View key={i} style={styles.section} wrap>
        <Text style={styles.kicker}>SECTION {String(i + 1).padStart(2, "0")}</Text>
        <Text style={styles.sectionTitle}>{section.title}</Text>
        <Text style={styles.intro}>{section.intro}</Text>
        {section.lessons?.map((lesson, j) => <View key={j} style={styles.lesson} wrap>
          <Text style={styles.lessonTitle}>{lesson.title}</Text>
          <Text style={styles.label}>Objective</Text>
          <Text style={styles.text}>{lesson.objective}</Text>
          <Text style={styles.text}>{lesson.summary}</Text>
          {lesson.keyPoints.length > 0 && <><Text style={styles.label}>Key points</Text>{lesson.keyPoints.map((x, k) => <Text key={k} style={styles.bullet}>• {x}</Text>)}</>}
          {lesson.examples.length > 0 && <><Text style={styles.label}>Examples</Text>{lesson.examples.map((x, k) => <Text key={k} style={styles.bullet}>• {x}</Text>)}</>}
          {lesson.exercise && <View style={styles.box}><Text style={styles.label}>Practice</Text><Text style={styles.text}>{lesson.exercise}</Text></View>}
        </View>)}
        {section.body?.map((x, j) => <Text key={j} style={styles.text}>{x}</Text>)}
      </View>)}
      <View style={styles.section}><Text style={styles.kicker}>FINAL CHECKLIST</Text>{doc.finalChecklist.map((x, i) => <Text key={i} style={styles.bullet}>• {x}</Text>)}</View>
      <Text style={styles.footer}>Generated by CourseForge · Source: {doc.source.title || doc.source.url}</Text>
    </Page>
  </Document>;
}
