export const BANNED_WORDS = [
  "can",
  "may",
  "just",
  "that",
  "very",
  "really",
  "literally",
  "probably",
  "basically",
  "could",
  "maybe",
  "massive",
  "delve",
  "embark",
  "esteemed",
  "shed light",
  "craft",
  "crafting",
  "imagine",
  "unlock",
  "discover",
  "skyrocket",
  "abyss",
  "not alone",
  "revolutionize",
  "disruptive",
  "utilize",
  "utilizing",
  "illuminate",
  "unveil",
  "pivotal",
  "intricate",
  "elucidate",
  "realm",
  "however",
  "harness",
  "exciting",
  "groundbreaking",
  "remarkable",
  "remains to be seen",
  "glimpse into",
  "stark",
  "testament",
  "in summary",
  "in conclusion",
  "opened up",
  "powerful",
  "dive deeper",
  "leverage",
  "tapestry",
  "robust",
  "navigate",
  "landscape",
  "nuanced",
  "streamline",
  "foster",
  "underscore",
  "multifaceted",
  "seamless",
  "ecosystem",
  "comprehensive",
  "facilitate",
  "beacon",
  "tailored",
  "elevate",
] as const;

export const WRITING_RULES_ITEMS = [
  "Write in active voice. Avoid passive voice.",
  "Use short, direct sentences.",
  "Use plain, simple words.",
  "Should use clear, simple language.",
  "Avoid metaphors and cliches.",
  "Avoid em dashes. Use commas, periods, or semicolons instead. Never use an em dash.",
  "Limit semicolons to one per paragraph.",
  "Avoid generalization. State specifics.",
  "No hashtags, no markdown, no asterisks.",
  "Skip rhetorical question openers. Do not ask a question then answer it right away.",
  "Vary sentence length on purpose. Mix short lines with longer ones.",
  "Skip tidy three-item lists for every point. Vary the count.",
  "Skip a wrap-up sentence that restates the point at the end.",
  "Take a side instead of hedging. Do not stack qualifiers in one sentence.",
  "Skip sign-offs that offer further help.",
  "Limit the 'not X, but Y' pattern to one or two uses per page.",
  "Write in first person when the voice calls for a person, not a system.",
  "Skip exclamation marks used as filler enthusiasm.",
  "Skip perfectly balanced pro-con endings for every question. Commit to a view sometimes.",
] as const;

export const WRITING_RULES_PROMPT = `
MANDATORY WRITING RULES - YOU MUST FOLLOW EVERY SINGLE RULE WITHOUT EXCEPTION:
${WRITING_RULES_ITEMS.map((r, i) => `${i + 1}. ${r}`).join("\n")}

BANNED WORDS AND PHRASES:
Do not use these in any form, singular or plural, any tense, any suffix:
${BANNED_WORDS.join(", ")}.
Banned phrases: Do not use these, in any form.
`;
